pipeline {
    agent { label 'netligent' }

    environment {
        IMAGE_NAME = "simple-html"
        CONTAINER_NAME = "Web-Server-Container"
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build Docker Image') {
            steps {
                    sh "docker build -t ${IMAGE_NAME}:${env.BRANCH_NAME} ."
            }
        }

        stage('Stop Old Container') {
            steps {
                sh """
                docker stop ${CONTAINER_NAME} || true
                docker rm ${CONTAINER_NAME} || true
                """
            }
        }

        stage('Run Container') {
            steps {
                script {
                    def port = 8080
                    if (env.BRANCH_NAME == "develop") {
                        port = 8081
                    } else if (env.BRANCH_NAME.startsWith("feature")) {
                        port = 8082
                    }

                    sh """
                    docker run -d \
                      --name ${CONTAINER_NAME} \
                      -p ${port}:80 \
                      ${IMAGE_NAME}:${env.BRANCH_NAME}
                    """
                }
            }
        }
    }
}
